### ISSUE TITLE
[Select] Create select with custom option

### ISSUE THREAD

**Issue by adrianoresende** [rockcontent/rock-ui#8]
## Description

Chakra works with select native but not have options to work as searchable has is very useful for our products.

The founder said he is developing, I commented aksing if have ETA.
https://github.com/chakra-ui/chakra-ui/issues/140

For fast create the component, we can use lib `react-select` or `downshift` but have a comment about it that is interesting
https://github.com/chakra-ui/chakra-ui/issues/38#issuecomment-529144356

## Style

Since we have no UI, we can start with style the same Chakra.

That is, same style `select`:
https://next.chakra-ui.com/docs/form/select

And the dropdown, same style `menu`:
https://next.chakra-ui.com/docs/components/menu#just-another-example

**Comment by ileaugustin** [comment]
I think we should implement a wrapper over the react-select library, and skip adding the select wrapper from chakraui.
From the react-select library we can create as many versions as we want
 - simple select
 - select with search in the available options
 - select with async search, etc
I prefer this approach as the library does not wrap the select html tag.
So we have more options, when it comes to customizing and styling the component.

**Comment by maracaipe** [comment]
@ileaugustin 
Agreed. Since we start knowing that we will have heavily customized select components, it's better if we choose one versatile library to make this consistent across all components, which is the case of the react-select library.

**Comment by adrianoresende** [comment]
We need at least the native select for **a simple list** because of the **mobile**.

For a simple list, we can show personalized but for mobile, we can hide the custom options and show the native.

WDYT?

**Comment by ileaugustin** [comment]
If we need the native select for the mobile versions, then we could:
- wrap the select component from chakra, which gives us the native select
- wrap the react-select to get the following components: Select, Async Select, Creatable, Async Creatable.

This should cover most of the use cases.

The react-select library allows replacing various components, but this is an advanced topic, and I suggest we handle it later, if we ever need it.

**Comment by maracaipe** [comment]
We should go on your suggestion. Native select from chakra and the rest with react-select.
